In [1]:
import pandas as pd

In [23]:
df = pd.read_csv('macro_data_gold.csv')
df

,Unnamed: 0,GS10,GS2,T10Y2YM,BAMLC0A2CAAEY,BAMLC0A4CBBBEY,FEDFUNDS,CORESTICKM159SFRBATL,DPCCRV1Q225SBEA,EXPINF1YR,...,PCOPPUSDM,POILWTIUSDM,PCOALAUUSDM,PALUMUSDM,PIORECRUSDM,RTWEXBGS,UNRATE,A191RP1Q027SBEA,B075RC1Q027SBEA,GOLD
0,2013-01-01,1.91,0.27,1.64,1.99,3.34,0.14,2.068297,1.6,1.315585,...,8053.738636,94.729565,96.952110,2037.606818,150.490909,87.4148,8.0,5.2,297.021,4.76
1,2013-02-01,1.98,0.27,1.71,2.14,3.43,0.15,2.146017,1.6,1.360807,...,8060.925000,95.309500,100.347321,2053.595000,154.638889,88.2863,7.7,5.2,297.021,4.84
2,2013-03-01,1.96,0.26,1.70,2.05,3.34,0.14,2.099902,1.6,1.004941,...,7652.375000,93.199048,97.316786,1911.282500,139.870000,88.7735,7.5,5.2,297.021,4.90
3,2013-04-01,1.76,0.23,1.53,2.09,3.36,0.15,1.935432,1.2,1.456315,...,7221.161905,92.067727,93.233163,1861.023810,137.390909,88.0315,7.6,1.7,293.197,5.00
4,2013-05-01,1.93,0.25,1.68,1.94,3.18,0.11,1.907797,1.2,1.178025,...,7248.714286,94.766957,93.126020,1832.571429,124.009524,88.4322,7.5,1.7,293.197,4.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2022-08-01,2.90,3.25,-0.35,3.71,4.70,2.33,5.990544,4.7,3.377132,...,7990.812174,93.692609,447.447565,2433.916087,109.065217,117.0619,3.7,7.7,340.564,4.12
116,2022-09-01,3.52,3.86,-0.34,4.34,5.33,2.56,6.393735,4.7,4.179150,...,7746.011364,84.400000,467.783673,2224.755909,100.840909,119.9764,3.5,7.7,340.564,4.12
117,2022-10-01,3.98,4.38,-0.40,4.34,5.33,3.08,6.367826,4.7,2.881959,...,7651.082857,87.286667,426.909184,2255.535238,94.619048,121.4764,3.7,7.7,340.564,4.12
118,2022-11-01,3.89,4.50,-0.61,5.25,6.32,3.78,6.475764,4.7,3.239048,...,8049.861364,84.076364,368.258279,2350.716364,94.568182,118.8233,3.6,7.7,340.564,4.12
119,2022-12-01,3.62,4.29,-0.67,4.60,5.55,4.10,6.606693,4.7,2.868119,...,8049.861364,84.076364,368.258279,2350.716364,94.568182,116.3915,3.5,7.7,340.564,4.12

In [3]:
ch = pd.read_excel('China_GDP_Growth.xlsx')

In [5]:
ch.rename(columns = {'기간':'date','성장률':'China GDP Growth'}, inplace=True)

In [7]:
ch = ch.iloc[::-1]

In [9]:
ch = ch.set_index(pd.to_datetime(ch['date']))

In [11]:
del ch['date']

In [18]:
ch

            China GDP Growth
date
2013-12-01             0.018
2014-03-01             0.014
2014-06-01             0.020
2014-09-01             0.019
2014-12-01             0.015
2015-03-01             0.013
2015-06-01             0.017
2015-09-01             0.018
2015-12-01             0.016
2016-03-01             0.011
2016-06-01             0.018
2016-09-01             0.018
2016-12-01             0.017
2017-03-01             0.013
2017-06-01             0.017
2017-09-01             0.017
2017-12-01             0.016
2018-03-01             0.014
2018-06-01             0.018
2018-09-01             0.016
2018-12-01             0.015
2019-03-01             0.014
2019-06-01             0.016
2019-09-01             0.015
2019-12-01             0.015
2020-03-01            -0.098
2020-06-01             0.115
2020-09-01             0.027
2020-12-01             0.026
2021-03-01             0.006
2021-06-01             0.013
2021-09-01             0.002
2021-12-01             0.016
2022-03-01             0.013
2022-06-01            -0.026
2022-09-01             0.039
2022-12-01             0.000

In [24]:
df = df.rename(columns = {'Unnamed: 0':'date'})

In [25]:
df = df.set_index(pd.to_datetime(df['date']))
del df['date']

In [29]:
data = df.join(ch)

In [28]:
data = data.fillna(method = 'ffill')
data = data.dropna()
data

,GS10,GS2,T10Y2YM,BAMLC0A2CAAEY,BAMLC0A4CBBBEY,FEDFUNDS,CORESTICKM159SFRBATL,DPCCRV1Q225SBEA,EXPINF1YR,EXPINF5YR,...,POILWTIUSDM,PCOALAUUSDM,PALUMUSDM,PIORECRUSDM,RTWEXBGS,UNRATE,A191RP1Q027SBEA,B075RC1Q027SBEA,GOLD,China GDP Growth
date,,,,,,,,,,,,,,,,,,,,,
2013-12-01,2.90,0.34,2.56,2.45,3.87,0.09,1.871190,2.0,1.924031,1.686049,...,97.890455,89.444464,1739.810000,135.790476,89.0909,6.7,5.4,302.348,4.66,0.018
2014-01-01,2.86,0.39,2.47,2.45,3.87,0.07,1.821814,1.4,1.638245,1.715308,...,94.963043,87.973539,1727.411364,128.119048,89.9843,6.6,0.3,336.422,4.66,0.018
2014-02-01,2.71,0.33,2.38,2.45,3.87,0.07,1.789186,1.4,1.585828,1.632026,...,100.705000,83.027679,1695.165000,121.370000,90.1124,6.7,0.3,336.422,4.66,0.018
2014-03-01,2.72,0.40,2.32,2.45,3.87,0.08,1.820857,1.4,1.219462,1.568777,...,100.568095,79.753061,1705.366667,111.833333,89.9378,6.7,0.3,336.422,4.66,0.014
2014-04-01,2.71,0.42,2.29,2.56,3.71,0.09,2.025161,2.0,1.653011,1.741558,...,102.175000,78.520714,1810.675000,114.580952,89.4059,6.2,7.6,359.986,4.42,0.014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-01,2.90,3.25,-0.35,3.71,4.70,2.33,5.990544,4.7,3.377132,2.186986,...,93.692609,447.447565,2433.916087,109.065217,117.0619,3.7,7.7,340.564,4.12,-0.026
2022-09-01,3.52,3.86,-0.34,4.34,5.33,2.56,6.393735,4.7,4.179150,2.533063,...,84.400000,467.783673,2224.755909,100.840909,119.9764,3.5,7.7,340.564,4.12,0.039
2022-10-01,3.98,4.38,-0.40,4.34,5.33,3.08,6.367826,4.7,2.881959,2.400708,...,87.286667,426.909184,2255.535238,94.619048,121.4764,3.7,7.7,340.564,4.12,0.039
2022-11-01,3.89,4.50,-0.61,5.25,6.32,3.78,6.475764,4.7,3.239048,2.530584,...,84.076364,368.258279,2350.716364,94.568182,118.8233,3.6,7.7,340.564,4.12,0.039
2022-12-01,3.62,4.29,-0.67,4.60,5.55,4.10,6.606693,4.7,2.868119,2.268449,...,84.076364,368.258279,2350.716364,94.568182,116.3915,3.5,7.7,340.564,4.12,0.000