In [1]:
import pandas as pd
import numpy as np

In [4]:
infotable = pd.read_csv('./2022q4_form13f/INFOTABLE.tsv',sep='\t')

/var/folders/h2/xtv6rzm1081cpt_clcdbqmt00000gn/T/ipykernel_75195/2349675760.py:1: DtypeWarning: Columns (8,10) have mixed types. Specify dtype option on import or set low_memory=False.
  infotable = pd.read_csv('./2022q4_form13f/INFOTABLE.tsv',sep='\t')

In [11]:
infotable[infotable['NAMEOFISSUER'] == 'BERKSHIRE HATHAWAY INC DEL CL B NEW']

,ACCESSION_NUMBER,INFOTABLE_SK,NAMEOFISSUER,TITLEOFCLASS,CUSIP,VALUE,SSHPRNAMT,SSHPRNAMTTYPE,PUTCALL,INVESTMENTDISCRETION,OTHERMANAGER,VOTING_AUTH_SOLE,VOTING_AUTH_SHARED,VOTING_AUTH_NONE
18,0001954551-22-000008,74878548,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,613,2037,SH,NaN,SOLE,0,0,0,2037
190,0001954551-22-000007,74883717,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,574,2083,SH,NaN,SOLE,0,0,0,2083
278,0001954551-22-000006,74878669,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,1649,5885,SH,NaN,SOLE,0,0,0,5885
456,0001954551-22-000005,74885304,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,1675,4760,SH,NaN,SOLE,0,0,0,4760
484,0001954551-22-000004,74880773,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,1328,4784,SH,NaN,SOLE,0,0,0,4784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2542316,0001799284-22-000004,72327519,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,1375,5151,SH,NaN,SOLE,NaN,0,0,5151
2549114,0001409362-22-000005,72321541,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,4086,15301,SH,NaN,SOLE,0,15301,0,0
2551162,0001943228-22-000002,72339570,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,381,1425,SH,NaN,SOLE,0,1425,0,0
2552601,0001057395-22-000004,72340760,BERKSHIRE HATHAWAY INC DEL CL B NEW,Stock,084670702,17393,65141,SH,NaN,SOLE,NaN,65141,0,0
2556314,0001561790-22-000012,72339203,BERKSHIRE HATHAWAY INC DEL CL B NEW,Common Stock,084670702,30616,114659,SH,NaN,SOLE,NaN,114606,0,47

In [12]:
coverpage = pd.read_csv('./2022q4_form13f/COVERPAGE.tsv',sep='\t')

In [13]:
coverpage

,ACCESSION_NUMBER,REPORTCALENDARORQUARTER,ISAMENDMENT,AMENDMENTNO,AMENDMENTTYPE,CONFDENIEDEXPIRED,DATEDENIEDEXPIRED,DATEREPORTED,REASONFORNONCONFIDENTIALITY,FILINGMANAGER_NAME,FILINGMANAGER_STREET1,FILINGMANAGER_STREET2,FILINGMANAGER_CITY,FILINGMANAGER_STATEORCOUNTRY,FILINGMANAGER_ZIPCODE,REPORTTYPE,FORM13FFILENUMBER,PROVIDEINFOFORINSTRUCTION5,ADDITIONALINFORMATION
0,0001954551-22-000008,31-DEC-2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Warther Private Wealth, LLC",1075 W. MARKET ST,NaN,AKRON,OH,44313,13F HOLDINGS REPORT,028-22710,N,NaN
1,0001954551-22-000007,30-SEP-2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Warther Private Wealth, LLC",1075 W. MARKET ST,NaN,AKRON,OH,44313,13F HOLDINGS REPORT,028-22710,N,NaN
2,0001954551-22-000006,30-JUN-2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Warther Private Wealth, LLC",1075 W. MARKET ST,NaN,AKRON,OH,44313,13F HOLDINGS REPORT,028-22710,N,NaN
3,0001954551-22-000005,31-MAR-2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Warther Private Wealth, LLC",1075 W. MARKET ST,NaN,AKRON,OH,44313,13F HOLDINGS REPORT,028-22710,N,NaN
4,0001954551-22-000004,30-JUN-2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Warther Private Wealth, LLC",1075 W. MARKET ST,NaN,AKRON,OH,44313,13F HOLDINGS REPORT,028-22710,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9005,0001297731-22-000007,30-SEP-2022,Y,5.0,NEW HOLDINGS,NaN,NaN,NaN,NaN,Pensionfund DSM Netherlands,PO BOX 6500,NaN,HEERLEN,P7,6401 JH,13F HOLDINGS REPORT,028-10932,N,NaN
9006,0001297731-22-000006,30-SEP-2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pensionfund Sabic,HET OVERLOON 1,NaN,HEERLEN,P7,6411 TE,13F HOLDINGS REPORT,028-16852,N,NaN
9007,0001297731-22-000005,30-SEP-2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pensionfund DSM Netherlands,PO BOX 6500,NaN,HEERLEN,P7,6401 JH,13F HOLDINGS REPORT,028-10932,N,NaN
9008,0001547676-22-000012,30-SEP-2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Swedbank Robur Fonder AB,105 34,NaN,STOCKHOLM,V7,105 34,13F NOTICE,028-16445,N,NaN
9009,0001062993-22-020107,30-JUN-2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sunbelt Securities, Inc.","2700 POST OAK BLVD, SUITE 1700",NaN,HOUSTON,TX,77056,13F HOLDINGS REPORT,028-16583,N,NaN

In [14]:
SUBMISSION = pd.read_csv('./2022q4_form13f/SUBMISSION.tsv',sep='\t')

In [15]:
SUBMISSION

          ACCESSION_NUMBER  FILING_DATE SUBMISSIONTYPE      CIK PERIODOFREPORT
0     0001214659-22-012820  31-OCT-2022         13F-HR  1744091    30-SEP-2022
1     0001085146-22-003673  31-OCT-2022         13F-HR   801051    30-SEP-2022
2     0001912128-22-000005  31-OCT-2022         13F-HR  1912128    30-SEP-2022
3     0001172661-22-002265  31-OCT-2022         13F-HR  1887163    30-SEP-2022
4     0001945037-22-000002  31-OCT-2022         13F-HR  1945037    30-SEP-2022
...                    ...          ...            ...      ...            ...
9005  0001567619-22-021090  01-DEC-2022       13F-HR/A  1055964    31-MAR-2018
9006  0001085146-22-004224  01-DEC-2022       13F-HR/A  1418773    30-JUN-2021
9007  0001567619-22-021097  01-DEC-2022       13F-HR/A  1055964    31-DEC-2018
9008  0001085146-22-004226  01-DEC-2022       13F-HR/A  1418773    31-DEC-2021
9009  0001085146-22-004212  01-DEC-2022       13F-HR/A  1011659    30-JUN-2020

[9010 rows x 5 columns]

In [16]:
OTHERMANAGER = pd.read_csv('./2022q4_form13f/OTHERMANAGER.tsv',sep='\t')

In [17]:
OTHERMANAGER

,ACCESSION_NUMBER,OTHERMANAGER_SK,CIK,FORM13FFILENUMBER,NAME
0,0001390777-22-000118,142163,937729.0,028-10991,FAYEZ SAROFIM & CO
1,0001390777-22-000118,142162,1725296.0,028-18741,CENTERSQUARE INVESTMENT MANAGEMENT LLC
2,0001390777-22-000118,142164,1465109.0,028-13573,Neuberger Berman Group LLC
3,0001357643-22-000007,142141,1357550.0,NaN,Weiss Asset Management LP
4,0001357643-22-000006,142140,1357550.0,NaN,Weiss Asset Management LP
...,...,...,...,...,...
3910,0001905128-22-000005,138223,NaN,028-16230,Jackson Square
3911,0000796370-22-000008,138234,916542.0,028-05990,ACADIAN ASSET MANAGEMENT LLC
3912,0001911876-22-000041,138215,1911876.0,NaN,BSN CAPITAL PARTNERS Ltd
3913,0001911876-22-000040,138217,1911876.0,NaN,BSN CAPITAL PARTNERS Ltd
3914,0001547676-22-000012,138235,NaN,NaN,Swedbank AB (publ)